modLoader="javafml"
loaderVersion="${mod_forge_version}"
issueTrackerURL="https://minecraft.curseforge.com/projects/reap-mod/issues"
# logoFile="reap.png"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_vendor}"
# credits=""
updateJSONURL="https://maxhenkel.de/update/reap.json"
displayURL="https://minecraft.curseforge.com/projects/reap-mod"
description='''Harvest crops by right-clicking'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"